stages:
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download
  unzip:
    cmd: python stages/02_unzip.py
    deps:
      - stages/02_unzip.py
      - download
    outs:
      - raw
  build:
    cmd: python stages/03_build.py
    deps:
      - stages/03_build.py
      - raw
    outs:
      - brick
